services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    profiles:
      - dev
      - prod

  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - dev
      - prod

  scopus_paper_searcher:
    build:
      context: .
      target: scopus_paper_searcher
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - REDIS_URL=redis://redis/0
      - ELSAVIER_API_KEY=${ELSAVIER_API_KEY}
    profiles:
      - prod

  webpage_pdf_finders:
    build:
      context: .
      target: paper_scrapper
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./pdfs:/app/pdfs
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - REDIS_URL=redis://redis/0
    profiles:
      - prod

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
